@startuml
binary "A" as A
binary "B" as B
concise "RuningTaskName" as RuningTaskName

caption sample_uxTaskPriorityGet.c TaskSwitch Timing Diagram

scale 1 as 50 pixels

@0
B is low
A is high
RuningTaskName is A

@2
A is low
B is high
RuningTaskName is B

@4
B is low
A is high
RuningTaskName is A

@6
A is low
B is high
RuningTaskName is B

@7
B is {hidden}
A is {hidden}
RuningTaskName is {hidden}

@enduml
