name: PlantUML from .puml to .svg

on:
  push:
    paths:    [ "**.puml" ]
    branches: [ "main" ]
  pull_request:
    paths:    [ "**.puml" ]
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  puml2svg:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"

    steps:
      - uses: actions/checkout@v3
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: .
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
