name: PlantUML from .puml to .svg

on:
  push:
    paths:    [ "**.puml" ]
  workflow_dispatch:

jobs:
  puml2svg:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Generate SVG Diagrams training/02_Task_Control/1_vTaskDelay/MyTrace.puml
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg training/02_Task_Control/1_vTaskDelay/MyTrace.puml

      - name: Generate SVG Diagrams training/02_Task_Control/2_vTaskDelayUntil/MyTrace.puml
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg training/02_Task_Control/2_vTaskDelayUntil/MyTrace.puml

      - name: Generate SVG Diagrams training/02_Task_Control/3_xTaskDelayUntil/MyTrace.puml
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg training/02_Task_Control/3_xTaskDelayUntil/MyTrace.puml

      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate SVG files for PlantUML diagrams"
